### ISSUE TITLE
gdshortener output

### ISSUE THREAD

**Issue by rinzes** [torre76/gd_shortener#1]
I'm using your gdshortener and it works ok except I'm getting the following output ' ('http://is.gd/gzg9yF', None) and I'm not sure why the ,None

**Comment by torre76** [comment]
As stated into the [docs](http://pythonhosted.org//gdshortener/class.html) the _shorten_ method provide a double output:
- _the shortened url_
- _the stat url_ if you have required traceability, otherwise it is `None`

_LogStat_ is a service provided by [is.gd](http://is.gd/apishorteningreference.php).
